import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { GeistSans } from 'geist/font/sans';
import "./globals.css";
import { Navbar } from "@/components/atom/layout/navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (   
    <html lang="en" className="dark">
      <body className={`${GeistSans.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

